version: "3.8"
services:
  proyectos-monolitica:
    container_name: proyectos-micro
    image: proyectos-micro:v1
    build: 
      context: .
    ports: 
      - "4001:4001"  
    networks: 
      - proyectos-app  

networks: 
  proyectos-app: