version: "3.8"
services:
  proyectos-micro:
    container_name: proyectos-micro
    image: proyectos-micro:v1
    build: 
      context: .
    ports: 
      - "4001:4001"  
    networks: 
      - proyectos-app  
    environment: 
        - MONGO_URI=${MONGO_URI}
        - PORT= 4001
      
  balanceador:
    container_name: balanceador
    image: balanceador:v1
    build: 
      context: ./balanceador
    ports: 
      - "4002:80"  
    networks: 
      - proyectos-app  

networks: 
  proyectos-app: